kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.1.0/24"
  # disableDefaultCNI: true
nodes:
- role: control-plane
- role: worker
- role: worker
